# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Mar 22 21:34:25 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(419, 571)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setSpacing(9)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.txtId = QtGui.QLineEdit(self.centralwidget)
        self.txtId.setEnabled(True)
        self.txtId.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.txtId.setObjectName(_fromUtf8("txtId"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtId)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.txtFirstName = QtGui.QLineEdit(self.centralwidget)
        self.txtFirstName.setEnabled(True)
        self.txtFirstName.setObjectName(_fromUtf8("txtFirstName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtFirstName)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtLastName = QtGui.QLineEdit(self.centralwidget)
        self.txtLastName.setEnabled(True)
        self.txtLastName.setObjectName(_fromUtf8("txtLastName"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtLastName)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.txtSection = QtGui.QLineEdit(self.centralwidget)
        self.txtSection.setObjectName(_fromUtf8("txtSection"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtSection)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txtYear = QtGui.QLineEdit(self.centralwidget)
        self.txtYear.setObjectName(_fromUtf8("txtYear"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtYear)
        self.txtCourse = QtGui.QLineEdit(self.centralwidget)
        self.txtCourse.setObjectName(_fromUtf8("txtCourse"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtCourse)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnClear = QtGui.QPushButton(self.centralwidget)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.verticalLayout.addWidget(self.btnClear)
        self.btnSearch = QtGui.QPushButton(self.centralwidget)
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.verticalLayout.addWidget(self.btnSearch)
        self.btnExit = QtGui.QPushButton(self.centralwidget)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.verticalLayout.addWidget(self.btnExit)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnFirst = QtGui.QPushButton(self.centralwidget)
        self.btnFirst.setObjectName(_fromUtf8("btnFirst"))
        self.horizontalLayout.addWidget(self.btnFirst)
        self.btnNext = QtGui.QPushButton(self.centralwidget)
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.horizontalLayout.addWidget(self.btnNext)
        self.btnPrev = QtGui.QPushButton(self.centralwidget)
        self.btnPrev.setObjectName(_fromUtf8("btnPrev"))
        self.horizontalLayout.addWidget(self.btnPrev)
        self.btnLast = QtGui.QPushButton(self.centralwidget)
        self.btnLast.setObjectName(_fromUtf8("btnLast"))
        self.horizontalLayout.addWidget(self.btnLast)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAdd = QtGui.QPushButton(self.centralwidget)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnEdit = QtGui.QPushButton(self.centralwidget)
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.horizontalLayout_2.addWidget(self.btnEdit)
        self.btnUpdate = QtGui.QPushButton(self.centralwidget)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.horizontalLayout_2.addWidget(self.btnUpdate)
        self.btnDelete = QtGui.QPushButton(self.centralwidget)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAdd_Record = QtGui.QAction(MainWindow)
        self.actionAdd_Record.setObjectName(_fromUtf8("actionAdd_Record"))
        self.actionUpdate = QtGui.QAction(MainWindow)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionSave_2 = QtGui.QAction(MainWindow)
        self.actionSave_2.setObjectName(_fromUtf8("actionSave_2"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSearch = QtGui.QAction(MainWindow)
        self.actionSearch.setIconVisibleInMenu(True)
        self.actionSearch.setObjectName(_fromUtf8("actionSearch"))
        self.actionSave_3 = QtGui.QAction(MainWindow)
        self.actionSave_3.setObjectName(_fromUtf8("actionSave_3"))
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName(_fromUtf8("actionExit_2"))
        self.menuFile.addAction(self.actionSearch)
        self.menuFile.addAction(self.actionSave_3)
        self.menuFile.addAction(self.actionExit_2)
        self.menuEdit.addAction(self.actionAdd_Record)
        self.menuEdit.addAction(self.actionDelete)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btnClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.txtLastName.clear)
        QtCore.QObject.connect(self.btnClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.txtId.clear)
        QtCore.QObject.connect(self.btnClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.txtFirstName.clear)
        QtCore.QObject.connect(self.actionExit_2, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.btnClear, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txtId.setEnabled)
        QtCore.QObject.connect(self.btnClear, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txtFirstName.setEnabled)
        QtCore.QObject.connect(self.btnClear, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txtLastName.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_6.setText(_translate("MainWindow", "                   Student Information", None))
        self.label_3.setText(_translate("MainWindow", "ID Number:", None))
        self.label.setText(_translate("MainWindow", "First Name:", None))
        self.label_2.setText(_translate("MainWindow", "Last Name:", None))
        self.label_4.setText(_translate("MainWindow", "Section:", None))
        self.label_5.setText(_translate("MainWindow", "Year:", None))
        self.label_7.setText(_translate("MainWindow", "Course :", None))
        self.btnClear.setText(_translate("MainWindow", "Clear", None))
        self.btnSearch.setText(_translate("MainWindow", "Search", None))
        self.btnExit.setText(_translate("MainWindow", "Exit", None))
        self.btnFirst.setText(_translate("MainWindow", "First", None))
        self.btnNext.setText(_translate("MainWindow", "Next", None))
        self.btnPrev.setText(_translate("MainWindow", "Previous", None))
        self.btnLast.setText(_translate("MainWindow", "Last", None))
        self.btnAdd.setText(_translate("MainWindow", "Add Record", None))
        self.btnEdit.setText(_translate("MainWindow", "Edit", None))
        self.btnUpdate.setText(_translate("MainWindow", "Update", None))
        self.btnDelete.setText(_translate("MainWindow", "Delete", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionAdd_Record.setText(_translate("MainWindow", "Add Record", None))
        self.actionUpdate.setText(_translate("MainWindow", "Update", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete Record", None))
        self.actionSave_2.setText(_translate("MainWindow", "Save", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSearch.setText(_translate("MainWindow", "Search", None))
        self.actionSave_3.setText(_translate("MainWindow", "Save", None))
        self.actionExit_2.setText(_translate("MainWindow", "Exit", None))

